# Generated by Django 5.1.8 on 2025-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesetting',
            name='active_gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe (Global)'), ('paypal', 'PayPal (Global - Coming Soon)')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
