# Generated by Django 5.1.8 on 2025-12-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesetting',
            name='currency_code',
            field=models.CharField(default='NGN', help_text='ISO Code (e.g. NGN, USD, EUR)', max_length=10),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='currency_symbol',
            field=models.CharField(default='₦', help_text='Symbol to display (e.g. ₦, $, €)', max_length=10),
        ),
    ]
