# Generated by Django 5.2.7 on 2025-12-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_marketplacesetting_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
