# Generated by Django 5.2.7 on 2025-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_public_id_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public_id',
            field=models.BigIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
