# Generated by Django 5.2.7 on 2025-12-31 06:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
        ('store', '0009_alter_category_options_alter_deliverymethod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packing', 'Packing'), ('sent_to_warehouse', 'Sent to Warehouse'), ('received_at_warehouse', 'Received at Warehouse'), ('issue', 'Issue'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('inbound_carrier', models.CharField(blank=True, max_length=100)),
                ('inbound_tracking', models.CharField(blank=True, max_length=120)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_warehouse_at', models.DateTimeField(blank=True, null=True)),
                ('received_at_warehouse_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payoutrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-valid_from']},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='productinsight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('awaiting_sellers', 'Awaiting Sellers'), ('packing', 'Packing at Warehouse'), ('pending', 'Pending Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='awaiting_sellers', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_no'], name='store_order_trackin_67ff52_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='store_order_status_536f03_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller'], name='store_order_seller__0a3309_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='store_payme_referen_98d7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='store_payme_status_8d3786_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['public_id'], name='store_produ_public__bb3fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'is_active'], name='store_produ_seller__401dab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='store_produ_categor_591340_idx'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.order'),
        ),
        migrations.AddField(
            model_name='sellerfulfillment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_fulfillments', to='store.order'),
        ),
        migrations.AddField(
            model_name='sellerfulfillment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_fulfillments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerfulfillment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='accounts.sellerprofile'),
        ),
        migrations.AddField(
            model_name='sellerfulfillment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.warehouse'),
        ),
        migrations.AddField(
            model_name='marketplacesetting',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='store.warehouse'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.warehouse'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='store_shipm_order_i_88882e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='store_shipm_trackin_ad3b32_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'created_at'], name='store_order_order_i_db1d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['code'], name='store_order_code_64876a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfulfillment',
            index=models.Index(fields=['seller', 'status'], name='store_selle_seller__0d606d_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfulfillment',
            index=models.Index(fields=['order', 'status'], name='store_selle_order_i_8812c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfulfillment',
            index=models.Index(fields=['warehouse', 'status'], name='store_selle_warehou_7cb0ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerfulfillment',
            unique_together={('order', 'seller')},
        ),
    ]
