# Generated by Django 5.2.7 on 2025-10-07 23:40

import accounts.models
import django.core.validators
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_account_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Exact name registered with your bank.', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_account_number',
            field=models.CharField(help_text='Your bank account number (digits only).', max_length=50, validators=[django.core.validators.RegexValidator('^\\d{6,20}$', 'Enter a valid account number (6–20 digits).')]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_name',
            field=models.CharField(help_text='Name of your bank (e.g., GTBank, Access Bank).', max_length=150),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_license',
            field=models.FileField(blank=True, help_text='Optional business registration certificate (PDF, JPG, PNG, ≤5MB).', null=True, upload_to='seller_docs/', validators=[accounts.models.validate_file_extension, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='id_document',
            field=models.FileField(help_text='Government-issued ID (PDF, JPG, PNG, ≤5MB).', upload_to='seller_docs/', validators=[accounts.models.validate_file_extension, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_banner',
            field=models.ImageField(help_text='Upload store banner (JPG, JPEG, or PNG only, max 5MB).', upload_to='store_banners/', validators=[accounts.models.validate_file_extension, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_logo',
            field=models.ImageField(help_text='Upload store logo (JPG, JPEG, or PNG only, max 5MB).', upload_to='store_logos/', validators=[accounts.models.validate_file_extension, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='support_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Business contact number in international format (e.g. +2348012345678).', max_length=128, region=None),
        ),
    ]
