# Generated by Django 5.1.8 on 2025-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_sellerprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override global commission rate for this seller (e.g. 5.0 for 5%). Leave empty to use global default.', max_digits=5, null=True),
        ),
    ]
